import type { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { NavLinkType } from "@/components/NavLinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const homePageNavItems: NavLinkType[] = [
  { url: "/meals", text: "Browse Meals" },
  { url: "/community", text: "Foodies Community" },
];

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header navItems={homePageNavItems} />
        {children}
      </body>
    </html>
  );
}
